
services:
  - type: web
    name: cryptomind-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000 --app-dir backend
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: USE_TESTNET
        value: True
      - key: PYTHON_VERSION
        value: 3.10.0
